# Name of your workflow (shown in GitHub Actions UI)
name: Build Badminton Game System

# When should this pipeline run?
on:
  push:                 # Trigger when code is pushed
    branches: [ "main" ]  # Only run when pushing to main branch

# Define jobs (a pipeline can have multiple jobs)
jobs:
  build:
    runs-on: ubuntu-latest   # Use a fresh Ubuntu server provided by GitHub

    steps:
    
    # Step 1: Download your repository code into the runner
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build frontend Docker image
    - name: Build Admin Docker image
      run: |
        cd admin              # Go into frontend folder
        docker build -t admin .   # Build Docker image named "frontend-app"

    # Step 2: Build frontend Docker image
    - name: Build Scoreboard Docker image
      run: |
        cd scoreboard              # Go into frontend folder
        docker build -t scoreboard .   # Build Docker image named "frontend-app"

    # Step 3: Build backend Docker image
    - name: Build Server Docker image
      run: |
        cd server               # Go into backend folder
        docker build -t server .    # Build Docker image named "backend-app"